apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: longhorn
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'longhorn-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/devops-skill-experts/es-demo.git
        targetRevision: "{{name}}" #Based on environment
        path: '03-argocd-apps/manifests/longhorn'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: longhorn
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
